### ISSUE TITLE
ROCm is not actually supported

### ISSUE THREAD

**Issue by f1am3d** [facefusion/facefusion-docker#10]
https://github.com/facefusion/facefusion/blob/ea8ecf7db092054ad0c893baf49032f11dc2480a/facefusion/utilities.py#L234

**Comment by henryruhs** [comment]
Thanks for pointing this out. This is indeed just the pytorch backend mapping and only related to frame enhancer. From my understanding, pytorch is using their CUDA backend for ROCM - it is probably too much of an effort to create an alias.

Fixed via: https://github.com/facefusion/facefusion/commit/d81371faeaa2840d1f0cad161d7d28f0d4170586

Now you should be able to use ROCM for pytorch using the next branch by adding the FACEFUSION_VERSION.

```yml
services:
 facefusion-cpu:
  build:
   context: .
   dockerfile: Dockerfile.cpu
   args:
   - FACEFUSION_VERSION=next
  command: [ 'python', 'run.py' ]
  volumes:
  - .assets:/facefusion/.assets
  ports:
  - 7870:7860
  ```
