### ISSUE TITLE
container should run as non-root?

### ISSUE THREAD

**Issue by fahadshery** [facefusion/facefusion-docker#35]
Hi,

examined your Dockerfiles and I think if we add the following:
```
# Define environment variables for UID and GID and local timezone
ENV PUID=${PUID:-1000}
ENV PGID=${PGID:-1000}

# Create a group with the specified GID
RUN groupadd -g "${PGID}" appuser
# Create a user with the specified UID and GID
RUN useradd -m -s /bin/sh -u "${PUID}" -g "${PGID}" appuser

#Run application as non-root
USER appuser
```
we should be able to run the app as non-root user?

**Comment by henryruhs** [comment]
Hey,

I prefer to maintain the Dockerfiles this way and allow users to decide how to run them. While it may be a matter of personal taste, I find that configuring this through Docker Compose feels more elegant.

```
services:
  facefusion-cpu:
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
```
